// State de conductor
export const OBTENER_CONDUCTOR = 'OBTENER_CONDUCTOR';
export const OBTENER_CONDUCTOR_PERFIL = 'OBTENER_CONDUCTOR_PERFIL';
export const SELECCIONAR_NOTIFICACION = 'SELECCIONAR_NOTIFICACION';
